# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddb',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
